[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "https://job-hopper.io/:splat"
  status = 301
  force = true
  conditions = { Host = ["job-hopper.co", "www.job-hopper.co", "job-hopper.net", "www.job-hopper.net"] }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
 
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''
