import type { App } from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faTrash,
  faPlus,
  faCheck,
  faSpinner,
  faExclamationTriangle,
  faBookmark,
  faChevronLeft,
  faChevronRight,
  faLocationDot,
  faBuilding,
  faXmark,
  faCircleInfo,
  faCircleCheck,
  faEnvelope,
  faUserTie,
  faGlobeAmericas,
  faClock,
  faDownload,
  faArrowRight,
  faBars,
  faStar,
  faPaperPlane,
  faSliders,
  faCrosshairs,
  faLock,
  faChevronDown,
  faClipboardList,
  faArrowUpRightFromSquare,
  faSackDollar,
  faTag,
  faBell,
  faBellSlash,
  faCrown,
  faRotate,
  faHourglassHalf,
  faArrowRightArrowLeft,
  faCheckDouble,
} from '@fortawesome/free-solid-svg-icons'
import { faTiktok, faInstagram } from '@fortawesome/free-brands-svg-icons'

library.add(
  faTrash,
  faPlus,
  faCheck,
  faSpinner,
  faExclamationTriangle,
  faBookmark,
  faChevronLeft,
  faChevronRight,
  faLocationDot,
  faBuilding,
  faXmark,
  faCircleInfo,
  faCircleCheck,
  faEnvelope,
  faUserTie,
  faGlobeAmericas,
  faClock,
  faDownload,
  faArrowRight,
  faBars,
  faStar,
  faPaperPlane,
  faSliders,
  faCrosshairs,
  faLock,
  faChevronDown,
  faClipboardList,
  faArrowUpRightFromSquare,
  faSackDollar,
  faTag,
  faBell,
  faBellSlash,
  faCrown,
  faRotate,
  faHourglassHalf,
  faArrowRightArrowLeft,
  faCheckDouble,
  faTiktok,
  faInstagram,
)

export function registerFontAwesome(app: App) {
  app.component('font-awesome-icon', FontAwesomeIcon)
}

