create type "public"."bd_leads_status" as enum ('New', 'Ready to Process', 'Processed', 'NOT FOUND', 'Ready for AI Personalization', 'Invalid Email');

create sequence "public"."enriched_lead_id_seq";


  create table "public"."bd_leads" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "Job Title" text,
    "Company Name" text,
    "Location" text,
    "Description" text,
    "Job Highlights" text,
    "Meta Data" text,
    "Extras" text,
    "Apply Link" text,
    "Apify Actor" text,
    "Apollo Employee Count" text,
    "Apify Employee Count" text,
    "Reason for Apollo" text,
    "apollo data" jsonb,
    "status" public.bd_leads_status default 'Ready to Process'::public.bd_leads_status
      );


alter table "public"."bd_leads" enable row level security;


  create table "public"."enriched_lead" (
    "id" integer not null default nextval('public.enriched_lead_id_seq'::regclass),
    "first_name" character varying(255),
    "last_name" character varying(255),
    "email" character varying(255),
    "headline" text,
    "description" text,
    "profile_url" text,
    "last_job_title" character varying(255),
    "last_job_description" text,
    "last_job_start_date" character varying,
    "address" text,
    "last_company_name" character varying(255),
    "last_company_url" text,
    "last_company_website" text,
    "last_company_description" text,
    "last_company_size" character varying(100),
    "last_company_industry" character varying(255),
    "last_company_address" text,
    "icypeas_meta_data" jsonb,
    "apollo_metadata" jsonb,
    "status" character varying(50),
    "job_post_row_id" integer,
    "emails" text
      );



  create table "public"."exclusion_lists" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "Job Title" text,
    "Company Name" text,
    "Location" text,
    "Description" text,
    "Job Highlights" text,
    "Meta Data" text,
    "Extras" text,
    "Apply Link" text,
    "Apify Actor" text,
    "Apollo Employee Count" text,
    "Apify Employee Count" text,
    "Reason for Apollo" text,
    "reason for reject" text,
    "apollo data" jsonb
      );


alter table "public"."exclusion_lists" enable row level security;


  create table "public"."job_hopper_live" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "Job Title" text,
    "Company Name" text,
    "Location" text,
    "Description" text,
    "Job Highlights" text,
    "Meta Data" text,
    "Extras" text,
    "Apply Link" text,
    "Apify Actor" text,
    "Apollo Employee Count" text,
    "Apify Employee Count" text,
    "apollo data" jsonb
      );


alter table "public"."job_hopper_live" enable row level security;


  create table "public"."raw_jobs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "Job Title" text,
    "Company Name" text,
    "Location" text,
    "Description" text,
    "Job Highlights" text,
    "Meta Data" text,
    "Extras" text,
    "Apply Link" text,
    "Apify Actor" text,
    "Apollo Employee Count" text,
    "Apify Employee Count" text,
    "Reason for Apollo" text,
    "Industry" text,
    "apollo data" jsonb
      );


alter table "public"."raw_jobs" enable row level security;


  create table "public"."sic_codes" (
    "csv_industry_code" text,
    "ewb_industry_code" text,
    "industry_title" text
      );


alter table "public"."sic_codes" enable row level security;

alter sequence "public"."enriched_lead_id_seq" owned by "public"."enriched_lead"."id";

CREATE UNIQUE INDEX be_leads_pkey ON public.bd_leads USING btree (id);

CREATE UNIQUE INDEX enriched_lead_email_key ON public.enriched_lead USING btree (email);

CREATE UNIQUE INDEX enriched_lead_pkey ON public.enriched_lead USING btree (id);

CREATE UNIQUE INDEX exclusion_lists_pkey ON public.exclusion_lists USING btree (id);

CREATE INDEX idx_enriched_lead_email ON public.enriched_lead USING btree (email);

CREATE UNIQUE INDEX job_hopper_live_pkey ON public.job_hopper_live USING btree (id);

CREATE UNIQUE INDEX raw_jobs_pkey ON public.raw_jobs USING btree (id);

alter table "public"."bd_leads" add constraint "be_leads_pkey" PRIMARY KEY using index "be_leads_pkey";

alter table "public"."enriched_lead" add constraint "enriched_lead_pkey" PRIMARY KEY using index "enriched_lead_pkey";

alter table "public"."exclusion_lists" add constraint "exclusion_lists_pkey" PRIMARY KEY using index "exclusion_lists_pkey";

alter table "public"."job_hopper_live" add constraint "job_hopper_live_pkey" PRIMARY KEY using index "job_hopper_live_pkey";

alter table "public"."raw_jobs" add constraint "raw_jobs_pkey" PRIMARY KEY using index "raw_jobs_pkey";

alter table "public"."enriched_lead" add constraint "enriched_lead_email_key" UNIQUE using index "enriched_lead_email_key";

grant delete on table "public"."bd_leads" to "anon";

grant insert on table "public"."bd_leads" to "anon";

grant references on table "public"."bd_leads" to "anon";

grant select on table "public"."bd_leads" to "anon";

grant trigger on table "public"."bd_leads" to "anon";

grant truncate on table "public"."bd_leads" to "anon";

grant update on table "public"."bd_leads" to "anon";

grant delete on table "public"."bd_leads" to "authenticated";

grant insert on table "public"."bd_leads" to "authenticated";

grant references on table "public"."bd_leads" to "authenticated";

grant select on table "public"."bd_leads" to "authenticated";

grant trigger on table "public"."bd_leads" to "authenticated";

grant truncate on table "public"."bd_leads" to "authenticated";

grant update on table "public"."bd_leads" to "authenticated";

grant delete on table "public"."bd_leads" to "service_role";

grant insert on table "public"."bd_leads" to "service_role";

grant references on table "public"."bd_leads" to "service_role";

grant select on table "public"."bd_leads" to "service_role";

grant trigger on table "public"."bd_leads" to "service_role";

grant truncate on table "public"."bd_leads" to "service_role";

grant update on table "public"."bd_leads" to "service_role";

grant delete on table "public"."enriched_lead" to "anon";

grant insert on table "public"."enriched_lead" to "anon";

grant references on table "public"."enriched_lead" to "anon";

grant select on table "public"."enriched_lead" to "anon";

grant trigger on table "public"."enriched_lead" to "anon";

grant truncate on table "public"."enriched_lead" to "anon";

grant update on table "public"."enriched_lead" to "anon";

grant delete on table "public"."enriched_lead" to "authenticated";

grant insert on table "public"."enriched_lead" to "authenticated";

grant references on table "public"."enriched_lead" to "authenticated";

grant select on table "public"."enriched_lead" to "authenticated";

grant trigger on table "public"."enriched_lead" to "authenticated";

grant truncate on table "public"."enriched_lead" to "authenticated";

grant update on table "public"."enriched_lead" to "authenticated";

grant delete on table "public"."enriched_lead" to "service_role";

grant insert on table "public"."enriched_lead" to "service_role";

grant references on table "public"."enriched_lead" to "service_role";

grant select on table "public"."enriched_lead" to "service_role";

grant trigger on table "public"."enriched_lead" to "service_role";

grant truncate on table "public"."enriched_lead" to "service_role";

grant update on table "public"."enriched_lead" to "service_role";

grant delete on table "public"."exclusion_lists" to "anon";

grant insert on table "public"."exclusion_lists" to "anon";

grant references on table "public"."exclusion_lists" to "anon";

grant select on table "public"."exclusion_lists" to "anon";

grant trigger on table "public"."exclusion_lists" to "anon";

grant truncate on table "public"."exclusion_lists" to "anon";

grant update on table "public"."exclusion_lists" to "anon";

grant delete on table "public"."exclusion_lists" to "authenticated";

grant insert on table "public"."exclusion_lists" to "authenticated";

grant references on table "public"."exclusion_lists" to "authenticated";

grant select on table "public"."exclusion_lists" to "authenticated";

grant trigger on table "public"."exclusion_lists" to "authenticated";

grant truncate on table "public"."exclusion_lists" to "authenticated";

grant update on table "public"."exclusion_lists" to "authenticated";

grant delete on table "public"."exclusion_lists" to "service_role";

grant insert on table "public"."exclusion_lists" to "service_role";

grant references on table "public"."exclusion_lists" to "service_role";

grant select on table "public"."exclusion_lists" to "service_role";

grant trigger on table "public"."exclusion_lists" to "service_role";

grant truncate on table "public"."exclusion_lists" to "service_role";

grant update on table "public"."exclusion_lists" to "service_role";

grant delete on table "public"."job_hopper_live" to "anon";

grant insert on table "public"."job_hopper_live" to "anon";

grant references on table "public"."job_hopper_live" to "anon";

grant select on table "public"."job_hopper_live" to "anon";

grant trigger on table "public"."job_hopper_live" to "anon";

grant truncate on table "public"."job_hopper_live" to "anon";

grant update on table "public"."job_hopper_live" to "anon";

grant delete on table "public"."job_hopper_live" to "authenticated";

grant insert on table "public"."job_hopper_live" to "authenticated";

grant references on table "public"."job_hopper_live" to "authenticated";

grant select on table "public"."job_hopper_live" to "authenticated";

grant trigger on table "public"."job_hopper_live" to "authenticated";

grant truncate on table "public"."job_hopper_live" to "authenticated";

grant update on table "public"."job_hopper_live" to "authenticated";

grant delete on table "public"."job_hopper_live" to "service_role";

grant insert on table "public"."job_hopper_live" to "service_role";

grant references on table "public"."job_hopper_live" to "service_role";

grant select on table "public"."job_hopper_live" to "service_role";

grant trigger on table "public"."job_hopper_live" to "service_role";

grant truncate on table "public"."job_hopper_live" to "service_role";

grant update on table "public"."job_hopper_live" to "service_role";

grant delete on table "public"."raw_jobs" to "anon";

grant insert on table "public"."raw_jobs" to "anon";

grant references on table "public"."raw_jobs" to "anon";

grant select on table "public"."raw_jobs" to "anon";

grant trigger on table "public"."raw_jobs" to "anon";

grant truncate on table "public"."raw_jobs" to "anon";

grant update on table "public"."raw_jobs" to "anon";

grant delete on table "public"."raw_jobs" to "authenticated";

grant insert on table "public"."raw_jobs" to "authenticated";

grant references on table "public"."raw_jobs" to "authenticated";

grant select on table "public"."raw_jobs" to "authenticated";

grant trigger on table "public"."raw_jobs" to "authenticated";

grant truncate on table "public"."raw_jobs" to "authenticated";

grant update on table "public"."raw_jobs" to "authenticated";

grant delete on table "public"."raw_jobs" to "service_role";

grant insert on table "public"."raw_jobs" to "service_role";

grant references on table "public"."raw_jobs" to "service_role";

grant select on table "public"."raw_jobs" to "service_role";

grant trigger on table "public"."raw_jobs" to "service_role";

grant truncate on table "public"."raw_jobs" to "service_role";

grant update on table "public"."raw_jobs" to "service_role";

grant delete on table "public"."sic_codes" to "anon";

grant insert on table "public"."sic_codes" to "anon";

grant references on table "public"."sic_codes" to "anon";

grant select on table "public"."sic_codes" to "anon";

grant trigger on table "public"."sic_codes" to "anon";

grant truncate on table "public"."sic_codes" to "anon";

grant update on table "public"."sic_codes" to "anon";

grant delete on table "public"."sic_codes" to "authenticated";

grant insert on table "public"."sic_codes" to "authenticated";

grant references on table "public"."sic_codes" to "authenticated";

grant select on table "public"."sic_codes" to "authenticated";

grant trigger on table "public"."sic_codes" to "authenticated";

grant truncate on table "public"."sic_codes" to "authenticated";

grant update on table "public"."sic_codes" to "authenticated";

grant delete on table "public"."sic_codes" to "service_role";

grant insert on table "public"."sic_codes" to "service_role";

grant references on table "public"."sic_codes" to "service_role";

grant select on table "public"."sic_codes" to "service_role";

grant trigger on table "public"."sic_codes" to "service_role";

grant truncate on table "public"."sic_codes" to "service_role";

grant update on table "public"."sic_codes" to "service_role";


