create type "public"."pay_type" as enum ('hour', 'year');

create type "public"."role_category" as enum ('operations', 'maintenance', 'engineering', 'management', 'executive', 'other');

drop index if exists "public"."job_matches_profile_job_key";


  create table "public"."scraper_search_terms" (
    "id" bigint generated by default as identity not null,
    "search_term" character varying not null default ''::character varying
      );


alter table "public"."scraper_search_terms" enable row level security;

alter table "public"."job_hopper_live" drop column "Apify Actor";

alter table "public"."job_hopper_live" drop column "Apify Employee Count";

alter table "public"."job_hopper_live" drop column "Apollo Employee Count";

alter table "public"."job_hopper_live" drop column "Apply Link";

alter table "public"."job_hopper_live" drop column "Company Name";

alter table "public"."job_hopper_live" drop column "Description";

alter table "public"."job_hopper_live" drop column "Extras";

alter table "public"."job_hopper_live" drop column "Job Highlights";

alter table "public"."job_hopper_live" drop column "Job Title";

alter table "public"."job_hopper_live" drop column "Location";

alter table "public"."job_hopper_live" drop column "Meta Data";

alter table "public"."job_hopper_live" drop column "apollo data";

alter table "public"."job_hopper_live" add column "ai_job_briefing" text not null;

alter table "public"."job_hopper_live" add column "apply_link" text;

alter table "public"."job_hopper_live" add column "company_name" text not null;

alter table "public"."job_hopper_live" add column "description" text;

alter table "public"."job_hopper_live" add column "employee_count" integer;

alter table "public"."job_hopper_live" add column "employment_types" text[];

alter table "public"."job_hopper_live" add column "is_remote" boolean not null default false;

alter table "public"."job_hopper_live" add column "job_title" text not null;

alter table "public"."job_hopper_live" add column "location" text;

alter table "public"."job_hopper_live" add column "pay_max" real;

alter table "public"."job_hopper_live" add column "pay_min" real;

alter table "public"."job_hopper_live" add column "pay_type" public.pay_type;

alter table "public"."job_hopper_live" add column "posted_date" timestamp with time zone;

alter table "public"."job_hopper_live" add column "role_category" public.role_category not null;

alter table "public"."job_hopper_live" add column "schedules" text[];

alter table "public"."job_hopper_live" add column "subscription_tier" text not null;

alter table "public"."job_hopper_live" alter column "created_at" drop not null;

-- job_hopper_live.id and job_matches.job_id → uuid moved to 20260310220100_fix_job_hopper_live_id_to_uuid.sql

CREATE UNIQUE INDEX job_hopper_live_apply_link_key ON public.job_hopper_live USING btree (apply_link);

CREATE UNIQUE INDEX job_hopper_live_job_title_company_name_apply_link_key ON public.job_hopper_live USING btree (job_title, company_name, apply_link);

CREATE UNIQUE INDEX scraper_search_terms_pkey ON public.scraper_search_terms USING btree (id);

CREATE UNIQUE INDEX scraper_search_terms_search_term_key ON public.scraper_search_terms USING btree (search_term);

alter table "public"."scraper_search_terms" add constraint "scraper_search_terms_pkey" PRIMARY KEY using index "scraper_search_terms_pkey";

alter table "public"."job_hopper_live" add constraint "job_hopper_live_apply_link_key" UNIQUE using index "job_hopper_live_apply_link_key";

alter table "public"."job_hopper_live" add constraint "job_hopper_live_job_title_company_name_apply_link_key" UNIQUE using index "job_hopper_live_job_title_company_name_apply_link_key";

alter table "public"."job_hopper_live" add constraint "job_hopper_live_subscription_tier_fkey" FOREIGN KEY (subscription_tier) REFERENCES public.products(key) not valid;

alter table "public"."job_hopper_live" validate constraint "job_hopper_live_subscription_tier_fkey";

alter table "public"."scraper_search_terms" add constraint "scraper_search_terms_search_term_key" UNIQUE using index "scraper_search_terms_search_term_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.check_phone_available(phone_input text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  normalized_input text;
  taken boolean;
BEGIN
  IF phone_input IS NULL OR trim(phone_input) = '' THEN
    RETURN true;
  END IF;
  normalized_input := regexp_replace(trim(phone_input), '[^0-9]', '', 'g');
  IF length(normalized_input) < 10 THEN
    RETURN true;
  END IF;
  SELECT EXISTS(
    SELECT 1
    FROM profiles p
    WHERE p.phone_number IS NOT NULL
      AND trim(p.phone_number) <> ''
      AND regexp_replace(trim(p.phone_number), '[^0-9]', '', 'g') = normalized_input
  ) INTO taken;
  RETURN NOT taken;
END;
$function$
;

grant delete on table "public"."scraper_search_terms" to "anon";

grant insert on table "public"."scraper_search_terms" to "anon";

grant references on table "public"."scraper_search_terms" to "anon";

grant select on table "public"."scraper_search_terms" to "anon";

grant trigger on table "public"."scraper_search_terms" to "anon";

grant truncate on table "public"."scraper_search_terms" to "anon";

grant update on table "public"."scraper_search_terms" to "anon";

grant delete on table "public"."scraper_search_terms" to "authenticated";

grant insert on table "public"."scraper_search_terms" to "authenticated";

grant references on table "public"."scraper_search_terms" to "authenticated";

grant select on table "public"."scraper_search_terms" to "authenticated";

grant trigger on table "public"."scraper_search_terms" to "authenticated";

grant truncate on table "public"."scraper_search_terms" to "authenticated";

grant update on table "public"."scraper_search_terms" to "authenticated";

grant delete on table "public"."scraper_search_terms" to "service_role";

grant insert on table "public"."scraper_search_terms" to "service_role";

grant references on table "public"."scraper_search_terms" to "service_role";

grant select on table "public"."scraper_search_terms" to "service_role";

grant trigger on table "public"."scraper_search_terms" to "service_role";

grant truncate on table "public"."scraper_search_terms" to "service_role";

grant update on table "public"."scraper_search_terms" to "service_role";


